# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20170607_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='tiempo',
            field=models.TimeField(null=True),
        ),
    ]
