# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0004_revision_tiempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='usuario',
            new_name='experimento',
        ),
        migrations.AddField(
            model_name='revision',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
