# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_auto_20170607_0734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tema',
            new_name='Author',
        ),
    ]
