# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_auto_20170607_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='mod_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='revision',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
